/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Cria um novo centro
 */
export const criarNovoCentroBody = zod.object({
  "centerId": zod.string(),
  "description": zod.string(),
  "state": zod.string(),
  "cluster": zod.enum(['DISTRIBUICAO', 'CROSS', 'CDFABRICA'])
})

export const criarNovoCentroResponse = zod.object({
  "centerId": zod.string(),
  "description": zod.string(),
  "state": zod.string(),
  "cluster": zod.enum(['DISTRIBUICAO', 'CROSS', 'CDFABRICA'])
})

/**
 * @summary Deleta um centro
 */
export const deletarCentroParams = zod.object({
  "centerId": zod.string()
})

/**
 * @summary Edita um centro
 */
export const editarCentroParams = zod.object({
  "centerId": zod.string()
})

export const editarCentroBodyClusterDefault = "distribuicao";

export const editarCentroBody = zod.object({
  "centerId": zod.string().optional().describe('ID do centro'),
  "description": zod.string().optional().describe('Descrição do centro'),
  "state": zod.string().optional().describe('Estado do centro'),
  "cluster": zod.string().default(editarCentroBodyClusterDefault).describe('Cluster do centro')
})

/**
 * @summary Define a configuração de impressão
 */
export const definirConfiguracaoImpressaoParams = zod.object({
  "centerId": zod.string()
})

export const definirConfiguracaoImpressaoBody = zod.object({
  "tipoImpressao": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "tipoQuebra": zod.enum(['LINHAS', 'PERCENTUAL']).nullable(),
  "quebraPalete": zod.boolean(),
  "valorQuebra": zod.number().nullable(),
  "separarPaleteFull": zod.boolean(),
  "separarUnidades": zod.boolean(),
  "exibirInfoCabecalho": zod.enum(['PRIMEIRO', 'TODOS', 'NENHUM']),
  "segregarFifo": zod.array(zod.string()),
  "dataMaximaPercentual": zod.number().nullable()
})

/**
 * @summary Busca as configurações de impressão
 */
export const buscarConfiguracoesImpressaoParams = zod.object({
  "centerId": zod.string()
})

export const buscarConfiguracoesImpressaoResponse = zod.object({
  "tipoImpressao": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "tipoQuebra": zod.enum(['LINHAS', 'PERCENTUAL']).nullable(),
  "quebraPalete": zod.boolean(),
  "valorQuebra": zod.number().nullable(),
  "separarPaleteFull": zod.boolean(),
  "separarUnidades": zod.boolean(),
  "exibirInfoCabecalho": zod.enum(['PRIMEIRO', 'TODOS', 'NENHUM']),
  "segregarFifo": zod.array(zod.string()),
  "dataMaximaPercentual": zod.number().nullable()
})

/**
 * @summary Busca todos os centros
 */
export const buscarTodosOsCentrosResponseItem = zod.object({
  "centerId": zod.string(),
  "description": zod.string(),
  "state": zod.string(),
  "cluster": zod.enum(['DISTRIBUICAO', 'CROSS', 'CDFABRICA'])
})
export const buscarTodosOsCentrosResponse = zod.array(buscarTodosOsCentrosResponseItem)

