/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export interface AddPauseGeralDto {
  /** ID do usuário que está cadastrando a pausa geral */
  cadastradoPorId: string;
  /** ID do centro que está sendo pausado */
  centerId: string;
  /** Turno da pausa geral */
  turno: string;
  /** Processo da pausa geral */
  processo: string;
  /** Segmento da pausa geral */
  segmento: string;
  /** Motivo da pausa geral */
  motivo: string;
}
