/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type CreateProdutoZodDtoSegmento = typeof CreateProdutoZodDtoSegmento[keyof typeof CreateProdutoZodDtoSegmento];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProdutoZodDtoSegmento = {
  SECO: 'SECO',
  REFR: 'REFR',
} as const;
