/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { CreateProdutoZodDtoTipoPeso } from './createProdutoZodDtoTipoPeso';
import type { CreateProdutoZodDtoSegmento } from './createProdutoZodDtoSegmento';
import type { CreateProdutoZodDtoEmpresa } from './createProdutoZodDtoEmpresa';

export interface CreateProdutoZodDto {
  sku: string;
  codEan?: string;
  codDum?: string;
  descricao: string;
  shelf: number;
  tipoPeso: CreateProdutoZodDtoTipoPeso;
  pesoLiquidoCaixa: number;
  pesoLiquidoUnidade: number;
  unPorCaixa: number;
  caixaPorPallet: number;
  segmento: CreateProdutoZodDtoSegmento;
  empresa: CreateProdutoZodDtoEmpresa;
}
