/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export interface CreateProdutividadeDto {
  /** Data e hora de início da demanda */
  inicio: string;
  /** Processo que está sendo iniciado */
  processo: string;
  /** ID do funcionário que está iniciando o picking */
  funcionarioId: string;
  /** IDs das paletes que estão sendo iniciadas */
  paletesIds: string[];
  /** ID do centro que está iniciando o picking */
  centerId: string;
  /** Turno que está iniciando o picking */
  turno: string;
  /** Observação do picking */
  obs: string;
}
