/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type DefinirConfiguracaoImpressaoDtoTipoQuebra = typeof DefinirConfiguracaoImpressaoDtoTipoQuebra[keyof typeof DefinirConfiguracaoImpressaoDtoTipoQuebra] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DefinirConfiguracaoImpressaoDtoTipoQuebra = {
  LINHAS: 'LINHAS',
  PERCENTUAL: 'PERCENTUAL',
} as const;
