/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { DefinirConfiguracaoImpressaoDtoTipoImpressao } from './definirConfiguracaoImpressaoDtoTipoImpressao';
import type { DefinirConfiguracaoImpressaoDtoTipoQuebra } from './definirConfiguracaoImpressaoDtoTipoQuebra';
import type { DefinirConfiguracaoImpressaoDtoExibirInfoCabecalho } from './definirConfiguracaoImpressaoDtoExibirInfoCabecalho';

export interface DefinirConfiguracaoImpressaoDto {
  tipoImpressao: DefinirConfiguracaoImpressaoDtoTipoImpressao;
  /** @nullable */
  tipoQuebra: DefinirConfiguracaoImpressaoDtoTipoQuebra;
  quebraPalete: boolean;
  /** @nullable */
  valorQuebra: number | null;
  separarPaleteFull: boolean;
  separarUnidades: boolean;
  exibirInfoCabecalho: DefinirConfiguracaoImpressaoDtoExibirInfoCabecalho;
  segregarFifo: string[];
  /** @nullable */
  dataMaximaPercentual: number | null;
}
