/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export interface EditarCentroDto {
  /** ID do centro */
  centerId?: string;
  /** Descrição do centro */
  description?: string;
  /** Estado do centro */
  state?: string;
  /** Cluster do centro */
  cluster?: string;
}
