/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export interface GetInfoDemandaResponseZodDto {
  id: number;
  placa: string;
  motorista: string;
  transportadora: string;
  cargaSegregada: boolean;
  retornoPalete: boolean;
  quantidadePaletes: number;
  status: string;
}
