/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type ListarNotasDemandaResponseZodDtoNotasItem = {
  id: number;
  viagemId: string;
  empresa: string;
  devolucaoDemandaId: number;
  notaFiscal: string;
  motivoDevolucao: string;
  /** @nullable */
  descMotivoDevolucao: string | null;
  /** @nullable */
  nfParcial: string | null;
  criadoEm: string;
  tipo: string;
};
