/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ListaDemandasZodDtoItemStatus } from './listaDemandasZodDtoItemStatus';

export type ListaDemandasZodDtoItem = {
  id: number;
  placa: string;
  motorista: string;
  data: string;
  conferenteId: string;
  doca: string;
  status: ListaDemandasZodDtoItemStatus;
  transportadora: string;
  cargaSegregada: boolean;
  retornoPalete: boolean;
  quantidadePaletes: number;
};
