/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type ListaDemandasZodDtoItemStatus = typeof ListaDemandasZodDtoItemStatus[keyof typeof ListaDemandasZodDtoItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListaDemandasZodDtoItemStatus = {
  AGUARDANDO_LIBERACAO: 'AGUARDANDO_LIBERACAO',
  AGUARDANDO_CONFERENCIA: 'AGUARDANDO_CONFERENCIA',
  EM_CONFERENCIA: 'EM_CONFERENCIA',
  CONFERENCIA_FINALIZADA: 'CONFERENCIA_FINALIZADA',
  FINALIZADO: 'FINALIZADO',
  CANCELADO: 'CANCELADO',
} as const;
