/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ListarFuncionariosPorCentroZodDtoOutputItemTurno } from './listarFuncionariosPorCentroZodDtoOutputItemTurno';
import type { ListarFuncionariosPorCentroZodDtoOutputItemRole } from './listarFuncionariosPorCentroZodDtoOutputItemRole';

export type ListarFuncionariosPorCentroZodDtoOutputItem = {
  id: string;
  name: string;
  centerId: string;
  turno: ListarFuncionariosPorCentroZodDtoOutputItemTurno;
  role: ListarFuncionariosPorCentroZodDtoOutputItemRole;
};
