/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type ResponseProdutoDtoEmpresa = typeof ResponseProdutoDtoEmpresa[keyof typeof ResponseProdutoDtoEmpresa];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseProdutoDtoEmpresa = {
  ITB: 'ITB',
  LDB: 'LDB',
  DPA: 'DPA',
} as const;
