/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ResponseProdutoDtoTipoPeso } from './responseProdutoDtoTipoPeso';
import type { ResponseProdutoDtoSegmento } from './responseProdutoDtoSegmento';
import type { ResponseProdutoDtoEmpresa } from './responseProdutoDtoEmpresa';

export interface ResponseProdutoDto {
  codEan?: string;
  codDum?: string;
  sku: string;
  descricao: string;
  shelf: number;
  tipoPeso: ResponseProdutoDtoTipoPeso;
  pesoLiquidoCaixa: number;
  pesoLiquidoUnidade: number;
  unPorCaixa: number;
  caixaPorPallet: number;
  segmento: ResponseProdutoDtoSegmento;
  empresa: ResponseProdutoDtoEmpresa;
  createdAt: string;
  updatedAt: string;
}
