/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ResumoDevolucaoDtoStatus } from './resumoDevolucaoDtoStatus';
import type { ResumoDevolucaoDtoNotasItem } from './resumoDevolucaoDtoNotasItem';
import type { ResumoDevolucaoDtoItensItem } from './resumoDevolucaoDtoItensItem';

export interface ResumoDevolucaoDto {
  temperaturaBau: number;
  temperaturaProduto: number;
  placa: string;
  motorista: string;
  transportadora: string;
  status: ResumoDevolucaoDtoStatus;
  operador: string;
  conferente: string;
  notas: ResumoDevolucaoDtoNotasItem[];
  itens: ResumoDevolucaoDtoItensItem[];
}
