/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ReturnInfoGeralRavexNotasItemTipo } from './returnInfoGeralRavexNotasItemTipo';
import type { ReturnInfoGeralRavexNotasItemItensItem } from './returnInfoGeralRavexNotasItemItensItem';

export type ReturnInfoGeralRavexNotasItem = {
  tipo: ReturnInfoGeralRavexNotasItemTipo;
  notaFiscal: string;
  /** @nullable */
  notaFiscalParcial?: string | null;
  motivoDevolucao: string;
  /** @nullable */
  descMotivoDevolucao: string | null;
  /** @nullable */
  operador?: string | null;
  itens: ReturnInfoGeralRavexNotasItemItensItem[];
};
