/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Adiciona um transporte
 */
export const adicionarTransporteParams = zod.object({
  "centerId": zod.string()
})

export const adicionarTransporteQueryParams = zod.object({
  "dataExpedicao": zod.iso.datetime({})
})

export const adicionarTransporteBodyItem = zod.object({
  "numeroTransporte": zod.string(),
  "nomeRota": zod.string().optional(),
  "nomeTransportadora": zod.string().optional(),
  "placa": zod.string().optional(),
  "prioridade": zod.number().optional(),
  "obs": zod.string().optional()
})
export const adicionarTransporteBody = zod.array(adicionarTransporteBodyItem)

/**
 * @summary Obtém os transportes por ids
 */
export const getTransportesByIdsBodyItem = zod.string()
export const getTransportesByIdsBody = zod.array(getTransportesByIdsBodyItem)

/**
 * @summary Adiciona paletes de separação
 */
export const adicionarPaletesSeparacaoBodyItem = zod.object({
  "transporteId": zod.string(),
  "id": zod.string(),
  "empresa": zod.string(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "quantidadePaletes": zod.number(),
  "enderecoVisitado": zod.number(),
  "segmento": zod.string(),
  "tipoProcesso": zod.string()
})
export const adicionarPaletesSeparacaoBody = zod.array(adicionarPaletesSeparacaoBodyItem)

/**
 * @summary Lista os transportes não cadastrados
 */
export const listarTransportesNaoCadastradosBodyItem = zod.string()
export const listarTransportesNaoCadastradosBody = zod.array(listarTransportesNaoCadastradosBodyItem)

/**
 * @summary Guarda as inte de separação
 */
export const transporteControllerGuardarIntesSeparacaoBodyItem = zod.object({

})
export const transporteControllerGuardarIntesSeparacaoBody = zod.array(transporteControllerGuardarIntesSeparacaoBodyItem)

/**
 * @summary Busca os itens por transporte
 */
export const transporteControllerBuscarItensPorTransporteParams = zod.object({
  "transporteId": zod.string()
})

export const transporteControllerBuscarItensPorTransporteResponseItem = zod.object({
  "codItem": zod.string(),
  "lote": zod.string(),
  "descricao": zod.string()
})
export const transporteControllerBuscarItensPorTransporteResponse = zod.array(transporteControllerBuscarItensPorTransporteResponseItem)

/**
 * @summary Busca os transportes por data
 */
export const transporteControllerBuscarTransportePorDataParams = zod.object({
  "centerId": zod.string()
})

export const transporteControllerBuscarTransportePorDataQueryParams = zod.object({
  "data": zod.string()
})

/**
 * @summary Lista os transportes com demanda iniciada
 */
export const listarTransportesComDemandaIniciadaBodyItem = zod.string()
export const listarTransportesComDemandaIniciadaBody = zod.array(listarTransportesComDemandaIniciadaBodyItem)

export const listarTransportesComDemandaIniciadaResponseItem = zod.string()
export const listarTransportesComDemandaIniciadaResponse = zod.array(listarTransportesComDemandaIniciadaResponseItem)

